#!/bin/bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

. ${DIR}/env.sh
: ${TCP_PORT:=9000}

echo REPO=${REPO}
nohup gh cs -R $REPO ports forward ${TCP_PORT}:${TCP_PORT} > ${TMPDIR}/nohup.txt 2>&1 &

${DIR}/cmd "nohup socat TCP-LISTEN:${TCP_PORT},reuseaddr,fork EXEC:"zls" > /var/log/zls.log 2>&1 &"
