name: Build Zig 0.14.1 and ZLS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ZLS
        uses: actions/checkout@v4
        with:
          repository: zigtools/zls
          path: zls

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake python3 git \
            libstdc++-12-dev curl xz-utils pkg-config

      - name: Download Zig 0.14.1 binary bootstrap
        run: |
          curl -LO https://ziglang.org/download/0.14.1/zig-x86_64-linux-0.14.1.tar.xz
          tar -xf zig-x86_64-linux-0.14.1.tar.xz
          #mv zig-x86_64-linux-0.14.1 zig-bootstrap
          echo "${PWD}/zig-x86_64-linux-0.14.1" >> $GITHUB_PATH

      #- name: Build Zig 0.14.1 from source
      #  run: |
      #    git clone --branch 0.14.1 https://github.com/ziglang/zig.git
      #    cd zig
      #    zig build -Drelease-safe
      #    # Optionally, add to PATH
      #    echo "$PWD/zig-out/bin" >> $GITHUB_PATH

      - name: Build ZLS with newly built Zig
        run: |
          cd zls
          zig build -Drelease-safe

      - name: Archive ZLS binary
        uses: actions/upload-artifact@v4
        with:
          name: zls
          path: zls/zig-out/bin/zls
